<a href="https://colab.research.google.com/github/RudhranB-07/JavaUstProjects/blob/main/LAP_Demo1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importing Packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# reading csv
data = pd.read_csv("/content/LoanApprovalPrediction.csv")

In [ ]:
#Displaying first few records
data.head(5) # first 5 records/ No number specified - by default 5

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [ ]:
# No of customers whole application Approved/Rejecetd
data["Loan_Status"].value_counts()

Loan_Status
Y    411
N    187
Name: count, dtype: int64

In [ ]:
# To show statistical rel btwn diff numeric colums of dataset
data.describe()

,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,586.000000,598.000000,598.000000,577.000000,584.000000,549.000000
mean,0.755973,5292.252508,1631.499866,144.968804,341.917808,0.843352
std,1.007751,5807.265364,2953.315785,82.704182,65.205994,0.363800
min,0.000000,150.000000,0.000000,9.000000,12.000000,0.000000
25%,0.000000,2877.500000,0.000000,100.000000,360.000000,1.000000
50%,0.000000,3806.000000,1211.500000,127.000000,360.000000,1.000000
75%,1.750000,5746.000000,2324.000000,167.000000,360.000000,1.000000
max,3.000000,81000.000000,41667.000000,650.000000,480.000000,1.000000

Some text

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [ ]:
data['Married'].unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
data['Married'] = le.fit_transform(data['Married'])

In [ ]:
data['Married'].unique()

array([0, 1])

In [ ]:
data['Gender'].unique()
data['Gender'] = le.fit_transform(data['Gender'])
data['Gender'].unique()

array([1, 0])

In [ ]:
data['Property_Area'].unique()
data['Property_Area'] = le.fit_transform(data['Property_Area'])
data['Property_Area'].unique()

array([2, 0, 1])

In [ ]:
data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,1,0,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,2,Y
1,LP001003,1,1,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,0,N
2,LP001005,1,1,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,2,Y
3,LP001006,1,1,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,2,Y
4,LP001008,1,0,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,2,Y

In [ ]:
data['Education'].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [ ]:
data['Education'] = le.fit_transform(data['Education'])
data['Education'].unique()

array([0, 1])

In [ ]:
data['Self_Employed'].unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
data['Self_Employed'] = le.fit_transform(data['Self_Employed'])
data['Self_Employed'].unique()

array([0, 1])

In [ ]:
data['Loan_Status'].unique()

array(['Y', 'N'], dtype=object)

In [ ]:
data['Loan_Status'] = le.fit_transform(data['Loan_Status'])
data['Loan_Status'].unique()

array([1, 0])

In [ ]:
data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,1,0,0.0,0,0,5849,0.0,NaN,360.0,1.0,2,1
1,LP001003,1,1,1.0,0,0,4583,1508.0,128.0,360.0,1.0,0,0
2,LP001005,1,1,0.0,0,1,3000,0.0,66.0,360.0,1.0,2,1
3,LP001006,1,1,0.0,1,0,2583,2358.0,120.0,360.0,1.0,2,1
4,LP001008,1,0,0.0,0,0,6000,0.0,141.0,360.0,1.0,2,1

In [ ]:
#Adding a column
data['Total_Income'] = data['ApplicantIncome'] + data['CoapplicantIncome']

In [ ]:
data.head()

In [1]:
#Dropping a column
data = data.drop(['ApplicantIncome'],axis=1)
data = data.drop(['CoapplicantIncome'],axis=1)

NameError: name 'data' is not defined

In [ ]:
data.head(5)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Total_Income
0,LP001002,1,0,0.0,0,0,NaN,360.0,1.0,2,1,5849.0
1,LP001003,1,1,1.0,0,0,128.0,360.0,1.0,0,0,6091.0
2,LP001005,1,1,0.0,0,1,66.0,360.0,1.0,2,1,3000.0
3,LP001006,1,1,0.0,1,0,120.0,360.0,1.0,2,1,4941.0
4,LP001008,1,0,0.0,0,0,141.0,360.0,1.0,2,1,6000.0